# frozen_string_literal: true

module ReactiveView
  module Types
    # Generates TypeScript type definitions from loader signatures.
    # Creates a .d.ts file that provides type safety for useLoaderData() calls.
    #
    # @example Generated output
    #   // Auto-generated by ReactiveView - DO NOT EDIT
    #
    #   export interface PagesUsersIdLoaderData {
    #     id: number;
    #     name: string;
    #     email?: string;
    #     tags: string[];
    #   }
    #
    #   export interface LoaderDataMap {
    #     "users/[id]": PagesUsersIdLoaderData;
    #   }
    #
    class TypescriptGenerator
      OUTPUT_FILE = 'src/lib/reactive-view/types/generated.d.ts'

      class << self
        # Generate TypeScript types for all loaders
        def generate
          new.generate
        end
      end

      def initialize
        @output_path = ReactiveView.configuration.working_directory_absolute_path.join(OUTPUT_FILE)
      end

      # Generate and write the TypeScript definitions
      #
      # @return [String] The generated TypeScript content
      def generate
        content = build_typescript

        # Ensure directory exists
        FileUtils.mkdir_p(@output_path.dirname)

        # Write the file
        File.write(@output_path, content)

        ReactiveView.logger.info "[ReactiveView] Generated TypeScript types at #{@output_path}"

        content
      end

      # Build TypeScript content without writing to file
      #
      # @return [String] The generated TypeScript content
      def build_typescript
        loaders = collect_loaders

        <<~TYPESCRIPT
          // Auto-generated by ReactiveView - DO NOT EDIT
          // Run `rails reactive_view:types:generate` to regenerate

          #{generate_interfaces(loaders)}

          #{generate_loader_map(loaders)}

          // Helper type for useLoaderData
          export type LoaderData<T extends keyof LoaderDataMap> = LoaderDataMap[T];
        TYPESCRIPT
      end

      private

      def collect_loaders
        LoaderRegistry.all_loader_paths.filter_map do |path|
          loader_class = LoaderRegistry.class_for_path(path)

          next unless loader_class._loader_sig

          {
            path: path,
            class_name: LoaderRegistry.path_to_class_name(path),
            interface_name: path_to_interface_name(path),
            schema: loader_class._loader_sig
          }
        end
      end

      def path_to_interface_name(path)
        segments = path.split('/').map do |segment|
          segment
            .gsub(/\[\.\.\.(.*?)\]/, '\1')
            .gsub(/\[\[(.*?)\]\]/, '\1')
            .gsub(/\[(.*?)\]/, '\1')
            .camelize
        end

        "#{segments.join}LoaderData"
      end

      def generate_interfaces(loaders)
        loaders.map do |loader|
          fields = schema_to_typescript_fields(loader[:schema])

          <<~TYPESCRIPT.strip
            export interface #{loader[:interface_name]} {
            #{fields.map { |f| "  #{f};" }.join("\n")}
            }
          TYPESCRIPT
        end.join("\n\n")
      end

      def generate_loader_map(loaders)
        entries = loaders.map do |loader|
          "  \"#{loader[:path]}\": #{loader[:interface_name]}"
        end

        <<~TYPESCRIPT.strip
          export interface LoaderDataMap {
          #{entries.join(";\n")};
          }
        TYPESCRIPT
      end

      def schema_to_typescript_fields(schema)
        return [] unless schema.respond_to?(:keys)

        schema.keys.map do |key|
          optional = key.type.optional? ? '?' : ''
          ts_type = dry_type_to_typescript(key.type)

          "#{key.name}#{optional}: #{ts_type}"
        end
      rescue StandardError => e
        ReactiveView.logger.warn "[ReactiveView] Error converting schema to TypeScript: #{e.message}"
        []
      end

      def dry_type_to_typescript(type)
        # Handle optional types
        if type.optional?
          inner = type.respond_to?(:right) ? type.right : type
          return "#{dry_type_to_typescript(inner)} | null"
        end

        # Get the primitive type name
        type_name = extract_type_name(type)

        case type_name
        when /String/i
          'string'
        when /Integer/i, /Float/i, /Decimal/i
          'number'
        when /Bool/i
          'boolean'
        when /Array/i
          member_type = extract_array_member_type(type)
          "#{dry_type_to_typescript(member_type)}[]"
        when /Hash/i
          if type.respond_to?(:keys) && type.keys.any?
            fields = schema_to_typescript_fields(type)
            "{ #{fields.join('; ')} }"
          else
            'Record<string, unknown>'
          end
        when /Date/i, /Time/i, /DateTime/i
          'string' # Dates serialize to ISO strings in JSON
        when /Any/i
          'unknown'
        when /Nil/i
          'null'
        else
          'unknown'
        end
      end

      def extract_type_name(type)
        type.class.name.to_s.split('::').last
      rescue StandardError
        'Any'
      end

      def extract_array_member_type(type)
        return Types::Any unless type.respond_to?(:type)

        type.type.respond_to?(:member) ? type.type.member : Types::Any
      rescue StandardError
        Types::Any
      end
    end
  end
end
