// Auto-generated by ReactiveView - DO NOT EDIT
// Run `rails reactive_view:types:generate` to regenerate

// This file will be populated with loader types when you run:
// rails reactive_view:types:generate

export interface LoaderDataMap {
  // Loader types will be added here
}

// Helper type for useLoaderData
export type LoaderData<T extends keyof LoaderDataMap> = LoaderDataMap[T];
